<?php
/* TITRES */
	/* NOM PAGES */
	define("_ACCUEIL", "Accueil");
	define("_LEPRINCIPE", "Le Principe");
	define("_EXPLORER", "Explorer");
	define("_PARTICIPERBD", "Participer à une bd");
	define("_CREERBD", "Créer une bd");
	define("_CONTACT", "Contact");
	define("_ABOUT", "A propos");
	define("_MENTIONS", "Mentions légales");
	define("_PARAM_BD", "Paramètre BD");
	define("_PROFIL", "Profil");
	define("_NOTIFICATIONS", "Page notifications");
	define("_PAGE_BD", "Page BD");
	define("_CONNEXION", "Connexion");
	define("_INSCRIPTION", "Inscription");


	define("_T_PRINCIPE", "Le Principe ?");
	define("_T_BDTERMINEES", "Bandes dessinées terminées");
	define("_T_BDENCOURS", "Bandes dessinées en cours...");

	define("_T_AMISILLUSTRATEURS", "Amis Illustrateurs !");

	define("_T_PARAM_BD", "Paramètre de la BD");
	
/* PARAGRAPHES */
	define("_P_BIENVENUE", "Bienvenue sur la plateforme de Bande dessinée collaborative");
	define("_PRINCIPE", "Créez une bd à plusieurs, une case chacun, chacun son tour !");
	define("_BDTERMINEES", "Consultez ici les dernières Bandes dessinées !");
	define("_P_CASERESERVEE", "Vous pouvez faire une demande de notification en cliquant sur “Participer à cette BD” pour être informé quand une case se libère.");
	define("_P_CASEDISPO", "Consultez ici les dernières Bandes dessinées !
	");
	define("_P_FOOTER", "Cette plateforme est notre bien commun et elle est vouée à évoluer.<br>
	Nous avons beaucoup d'autres idées pour l'améliorer et il ne manque<br>
	plus que les votres. N'hésitez pas à nous faire part de vos suggestions,<br>
	idées et remarques. Nous en prendrons note et nous ne le ferons jamais.<br>
	<br>
	Mais faites le quand même s'il vous plaît.");

/* BOUTONS */
	define("_TOUTVOIR", "Tout voir");
	define("_ENSAVOIRPLUS", "En savoir plus");
	define("_LIRE", "Lire la bd");
	define("_VALIDER", "Valider");
	define("_VALIDER_ET_COMMENCER", "Valider et commencer");
	define("_ACCEPTER", "Accepter");
	define("_REFUSER", "Refuser");
	define("_PARTICIPER_NOTIF", "Participer à cette BD");
	define("_NOUS_CONTACTER", "Nous contacter");

/* MESSAGES ERREURS */
	define("_ERREUR_CHAMPSVIDE", "Merci de remplir tous les champs");
	define("_ERREUR_PSEUDOVIDE", "Merci de saisir un pseudo");
	define("_ERREUR_MAILVIDE", "Merci de saisir un email");
	define("_ERREUR_MDPVIDE", "Merci de saisir un mot de passe");
	define("_ERREUR_TITREVIDE", "Merci de saisir un titre");
	define("_ERREUR_ETATVIDE", "Merci de choisir un état");
	define("_ERREUR_NBPAGEVIDE", "Merci de choisir un nombre de page");
	define("_ERREUR_TEMPSVIDE", "Merci de choisir un temps de réalisation d'une case");


	define("_ERREUR_SAISIEINCORRECTE", "Saisie incorrecte");
	define("_ERREUR_PSEUDOPRIT", "Ce Pseudo est déjà prit");
	define("_ERREUR_MAILPRIT", "Il existe déjà un compte avec cet email");
	define("_ERREUR_TITREPRIT", "Ce titre est déjà prit");
	
	define("_ERREUR_FORMATPSEUDO", "Format du pseudo invalide");
	define("_ERREUR_FORMATMAIL", "Format email invalide");
	define("_ERREUR_FORMATMDP", "Format mot de passe invalide");
	
	define("_ERREUR_DESCRIPTION", "Merci de saisir une description");
	define("_ERREUR_AVATARTRANSFERT", "Erreur transfert avatar");
	define("_ERREUR_FICHIERLOURD","Fichier trop lourd");
	define("_ERREUR_TAILLEIMG", "Taille image trop grande");
	define("_ERREUR_EXTENSION", "Extension doit être : ");

	define("_ERREUR_CONNECTPAGECREATION", "Veuillez-vous connecter pour créer une bd.");

	define("_MSG_AUCUNRESULTAT", "Aucun résultat ne correspond à votre recherche");

define("_BDENREGISTREE", "Bande dessinée enregistrée");

/* CHOIX */
	define("_TERMINEE", "Terminée");
	define("_ENCOURS", "En cours");

	define("_VISIBLE_TOUS", "Visible par tous");

	define("_ENTREPOTES", "Entre potes");
	define("_EXP_ENTREPOTES", "Vous seul pouvez choisir les participants. Idéal pour un projet entre amis");

	define("_OUVERTE", "Ouverte à tous");
	define("_EXP_OUVERTE", "Tout le monde peut participer à votre BD. N’essayez pas d’avoir le contrôle et laissez vous surprendre");

	define("_PRIVEE", "Privée");
	define("_EXP_PRIVEE", "Seulement vous et vos amis pouvez accéder à la BD. Pour laisser votre part d’ombre s’exprimer");
	define("_VISIBLE_PARTICIPANT", "Visible uniquement par les participants");

	define("_CASERESERVEE", "Case réservée");
	define("_CASERESERVEES", "Cases réservées");
	define("_CASEDISPO", "Case disponible");
	define("_CASEDISPOS", "Cases disponibles");

	define("_TRI_VUE", "Trier par nombre de vues");
/* PRINCIPE.PHP */
	define("_P_PRINCIPE", "Comme son nom l’indique à peu près, “Cadavre esquisse” s’inspire du principe du cadavre exquis transposé à la Bande dessinée. Dessinez une première case de BD et c’est au monde entier d’imaginer la suite !");
	define("_COMMENT", "Comment ça fonctionne ?");
	define("_P_ICONE1", "Créez un nouveau projet ou réservez une case d’un projet en cours");
	define("_P_ICONE2", "Définissez la forme de la case à réaliser et téléchargez le template");
	define("_P_ICONE3", "Utilisez votre logiciel de prédilection pour réaliser un chef-d’oeuvre !");
	define("_P_ICONE4", "Postez votre création et c’est au tour de celui qui voudra !");

	define("_REGLES", "Quelques règles et remarques :");
	define("_P_REGLE1", "En mode “Entre potes” et “Ouverte à tous”, les BD sont consultable par tous le monde.");
	define("_P_REGLE2", "En mode “Privé” les BD sont consultable uniquement par les participants.");
	define("_P_REGLE3", "Vous pouvez modifiez le “mode” de votre BD à tout moment.");
	define("_P_REGLE4", "C’est le créateur qui choisit le titre de la BD et qui peut mettre fin à la BD à tout moment");
	define("_P_REGLE5", "Différentes formes de case existent, certaines contraignent la forme de case suivante.");
	define("_P_REGLE6", "Vous avez un temps définit pour réaliser votre case. Auquel cas la case sera de nouveau disponible.");
	define("_P_REGLE7", "Vous pouvez participer autant de fois que vous le souhaitez à une bd");
/* PARTICIPER A UNE BD */
define("_T_PARTICIPER", "Choisissez une BD à laquelle vous voudriez participer :");

/* EXPLORER.PHP */
	define("_T_PARCOURIR", "Parcourez les différentes BD terminées ou en cours de création !");
	define("_BARRE_RECHERCHE", "Rechercher une bd, un auteur…");
	define("_CHAMPS_RECHERCHE_VIDE", "Champs de recherche vide");
/* FORMULAIRES */
	/* CREATION_BD.PHP */
		define("_T_CREATION", "Vous êtes en train de créer une BD");
		define("_CHAMP_TITRE", "Titre de votre BD");
		define("_SPAN_TITRE", "vous pourrez le modifier à tout moment");

		define("_LABEL_DROIT", "Choisissez l’état de votre BD");
		define("_LABEL_POTES", "Vous avez choisit la BD “Entre potes”");
		define("_SPAN_POTES", "Veuillez saisir le nom des participants :");
		define("_CHAMP_RECHERCHE", "Frédéric Lambda");

		define("_LABEL_TEMPS", "Temps de réalisation d’une case :");
		define("_SPAN_TEMPS", "Là c’est à vous de voir ! Entre la spontanéité ou le travail soigné. Ceci s’applique à l’ensemble des participants de la BD");
		define("_1HEURE", " heure");
		define("_HEURES", " heures");
		define("_1JOUR", " jour");
		define("_JOURS", " jours");
		define("_SEMAINE", " semaine");

		define("_LABEL_PAGE", "Nombre de page de la BD");
		define("_SPAN_PAGE", "Définissez le nombre de page de votre PROJEEEET !!!");
		define("_LABEL_VALIDER", "Comme c’est vous qui créé la BD, c’est à vous de commencer !");

/* NOTIFICATIONS */
	define("_ATTENTE_INVIT", "Invitation en attente");
	define("_MSG_ATTENTE_INVIT", " vous invite cordialement à participer à sa BD");
	define("_MSG_ACCEPTER", " a accepté de participer à votre BD");
	define("_MSG_REFUSER", " a refusé de participer à votre BD");
	define("_MSG_FIN_BD", " a mis fin à la BD ");
	define("_MSG_CASEDISPO", "Une case est disponible dans la BD ");
	define("_MSG_EXPIRATION1", "Le temps de réalisation de la case à expirer ! La case de la bd ");
	define("_MSG_EXPIRATION2", " est de nouveau disponible."); 
	define("_LABD", "La BD ");
	define("_EST_MAINTENANT", " est maintenant ");
	define("_MSG_NOUV_PARTICIPANT", " participe désormais à la BD ");

/* MOTS SEULS */
	define("_BIENVENUE", "Bienvenue ");
	define("_ETAT", "Etat : ");
	define("_NB_PARTICIPANTS", " participants");
	define("_NOM", "Nom");
	define("_MAIL", "Mail");
	define("_BLA", "Blablabla");
	define("_TITRE", "Titre");
	define("_MOTDEPASSE", "Mot de passe");
	define("_NOTIFICATION", "Notifications");
	define("_BANDES_DESSINEES", "Bandes Dessinées");
	define("_CASES", "Cases");
	define("_PARAMETRES", "Paramètres");
	define("_DECONNEXION", "Déconnexion");

define("_CONFIG_PARTICIPANTS", "Ajouter ou supprimer des participants");
define("_PARTICIPATIONS_BD", "participations à une BD");
define("_PARTICIPATIONSBD", "Participations BD");

define("_REJOIN_RESEAUX", "Rejoignez nous sur les réseaux sociaux");
define("_SUIVEZNOUS", "Suivez nous sur : ");


define("_CREE_LE", "Créé le ");
define("_CREATIONS_BD", "BD créées");
define("_CASES_REALISEES", "Cases réalisées");


define("_CONSIGNE_FORME", "Choisissez la forme de votre case");
define("_CASE_REALISE_PAR", "Case réalissée par ");
define("_CASE_RESERVEE_PAR", "Case réservée par ");
define("_RESERVER_CASE", "Réserver cette case");
define("_RESERVER_CASE_FAIT", "Vous avez réservé cette case !");
define("_INDICATION_PARTICIPER_NOTIF", "Vous recevrez un mail lorsqu’une case sera disponible");

define("_OUBLI_MDP", "Mot de passe oublié");

/* INSCRIPTION */

define("_AVATAR", "Choisissez votre avatar :");
define("_CHOIX_ETAT", "Choisisser l'état de votre bd : ");

define("_ENVOYER", "Envoyer");
define("_OBJET", "Objet");
?>
